### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true

### ISSUE THREAD

**Issue by ahmedgulabkhan** [theindianappguy/FlutterChatAppTutorial#1]
The following error shows while running the project with all the required dependencies. Error is present in the TextField() widget of the 'search.dart' file of this project.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

**Comment by akshaybalaji123** [comment]
@ahmedgulabkhan Launching lib\main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for sdk gphone x86 arm to report its views...
Debug service listening on ws://127.0.0.1:65280/yj6K69WaXFE=/ws
Syncing files to device sdk gphone x86 arm...

════════ Exception caught by widgets library 
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following FirebaseException was thrown building Builder:
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

The relevant error-causing widget was:
  MaterialApp file:///C:/Users/aksha/Downloads/chatapp/chat_app_tutorial/lib/main.dart:13:12

When the exception was thrown, this was the stack:
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
#2      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:37:47)
#3      new AuthMethods (package:chat_app_tutorial/services/auth.dart:6:42)
#4      new _SignupState (package:chat_app_tutorial/views/signup.dart:14:33)
#5      Signup.createState (package:chat_app_tutorial/views/signup.dart:7:33)
#6      new StatefulElement (package:flutter/src/widgets/framework.dart:4635:25)
#7      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:900:38)
...     Normal element mounting (132 frames)
#139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#140    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (258 frames)
#398    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#399    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#400    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#401    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#402    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1087:17)
#403    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#404    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1086:13)
#405    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:927:7)
#406    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:908:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════
═══════════════════════════════════════════════════════
The following FirebaseException was thrown building Builder:
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/aksha/Downloads/chatapp/chat_app_tutorial/lib/main.dart:13:12
When the exception was thrown, this was the stack: 
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
#2      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:37:47)
#3      new AuthMethods (package:chat_app_tutorial/services/auth.dart:6:42)
#4      new _SignupState (package:chat_app_tutorial/views/signup.dart:14:33)
...
I am getting this error
